database:
  type: "chromadb"
  path: "./vector_db"
  persist_directory: true
  collection_name: "mecademic_chunks"

embeddings:
  # BGE-M3 for document chunks (manuals, PDFs, general text)
  document_model:
    name: "BAAI/bge-m3"
    batch_size: 32
    device: "cpu"  # cpu/cuda
  
  # CodeBERT for code chunks (Python, C#, JavaScript, etc.)
  code_model:
    name: "microsoft/codebert-base"
    batch_size: 32
    device: "cpu"  # cpu/cuda

ingestion:
  source_directory: "./processed/semantic_chunks"
  validate_chunks: true
  skip_duplicates: true
  progress_reporting: true
  
  # Content type routing
  document_extensions: [".pdf", ".txt", ".md", ".html"]
  code_extensions: [".py", ".js", ".c", ".cpp", ".cs", ".java"]

search:
  default_limit: 10
  similarity_threshold: 0.05
  
storage:
  backup_directory: "./vector_db/backups"
  log_directory: "./vector_db/logs"